-- ═══════════════════════════════════════════════════════════════════
-- BASE VIEW 1: ORDER GRAIN (one row per order)
-- Used by: Dashboard 1, 2, 3
-- Grain: one order = one row
-- ═══════════════════════════════════════════════════════════════════

CREATE OR REPLACE VIEW ECOMMERCE_ANALYTICS.ANALYTICS.V_ORDER_ANALYTICS AS
WITH payment_agg AS (
    SELECT
        ORDER_ID,
        SUM(PAYMENT_VALUE) AS TOTAL_PAYMENT,
        COUNT(*) AS PAYMENT_SPLITS,
        MAX_BY(PAYMENT_TYPE, PAYMENT_VALUE) AS PRIMARY_PAYMENT_TYPE,
        MAX_BY(PAYMENT_INSTALLMENTS, PAYMENT_VALUE) AS PRIMARY_INSTALLMENTS
    FROM ECOMMERCE_ANALYTICS.RAW.PAYMENTS
    GROUP BY ORDER_ID
),
review_clean AS (
    SELECT
        ORDER_ID,
        REVIEW_SCORE
    FROM ECOMMERCE_ANALYTICS.RAW.REVIEWS
    QUALIFY ROW_NUMBER() OVER (PARTITION BY ORDER_ID ORDER BY REVIEW_CREATION_DATE DESC) = 1
),
item_summary AS (
    SELECT 
        ORDER_ID,
        COUNT(*) AS ITEMS_IN_ORDER,
        SUM(PRICE) AS TOTAL_ITEM_PRICE,
        SUM(FREIGHT_VALUE) AS TOTAL_FREIGHT,
        COUNT(DISTINCT PRODUCT_ID) AS DISTINCT_PRODUCTS
    FROM ECOMMERCE_ANALYTICS.RAW.ORDER_ITEMS
    GROUP BY ORDER_ID
),
customer_history AS (
    SELECT
        C.CUSTOMER_UNIQUE_ID,
        COUNT(DISTINCT O.ORDER_ID) AS LIFETIME_ORDERS,
        SUM(P.PAYMENT_VALUE) AS LIFETIME_VALUE,
        MIN(O.ORDER_PURCHASE_TIMESTAMP) AS FIRST_PURCHASE,
        MAX(O.ORDER_PURCHASE_TIMESTAMP) AS LAST_PURCHASE
    FROM ECOMMERCE_ANALYTICS.RAW.ORDERS O
    INNER JOIN ECOMMERCE_ANALYTICS.RAW.CUSTOMERS C ON O.CUSTOMER_ID = C.CUSTOMER_ID
    INNER JOIN ECOMMERCE_ANALYTICS.RAW.PAYMENTS P ON O.ORDER_ID = P.ORDER_ID
    WHERE O.ORDER_STATUS = 'delivered'
    GROUP BY C.CUSTOMER_UNIQUE_ID
)

SELECT
    O.ORDER_ID,
    O.ORDER_PURCHASE_TIMESTAMP,
    DATE_TRUNC('month',O.ORDER_PURCHASE_TIMESTAMP) AS ORDER_MONTH,
    QUARTER(O.ORDER_PURCHASE_TIMESTAMP) AS ORDER_QUARTER,
    YEAR(O.ORDER_PURCHASE_TIMESTAMP) AS ORDER_YEAR,
    DAYNAME(O.ORDER_PURCHASE_TIMESTAMP) AS DAY_OF_WEEK,
    C.CUSTOMER_UNIQUE_ID AS CUSTOMER_UNIQUE_ID,
    C.CUSTOMER_CITY AS CUSTOMER_CITY,
    C.CUSTOMER_STATE AS CUSTOMER_STATE,
    CH.LIFETIME_ORDERS AS CUSTOMER_ORDER_COUNT,
    CH.LIFETIME_VALUE AS LIFETIME_VALUE,
    CH.FIRST_PURCHASE AS FIRST_PURCHASE,
    CH.LAST_PURCHASE AS LAST_PURCHASE,
    CASE 
        WHEN CH.LIFETIME_ORDERS >= 4 THEN 'Loyal'
        WHEN CH.LIFETIME_ORDERS >= 2 THEN 'Returning'
        ELSE 'One-Time'
    END AS CUSTOMER_SEGMENT,
    ITS.ITEMS_IN_ORDER,
    ITS.DISTINCT_PRODUCTS,
    ITS.TOTAL_ITEM_PRICE,
    ITS.TOTAL_FREIGHT,
    PA.TOTAL_PAYMENT,
    PA.PRIMARY_PAYMENT_TYPE,
    PA.PRIMARY_INSTALLMENTS,
    PA.PAYMENT_SPLITS,
    RC.REVIEW_SCORE,

    DATEDIFF('day',O.ORDER_PURCHASE_TIMESTAMP,O.ORDER_DELIVERED_CUSTOMER_DATE) AS DELIVERY_DAYS,
    DATEDIFF('day',O.ORDER_PURCHASE_TIMESTAMP,O.ORDER_ESTIMATED_DELIVERY_DATE) AS ESTIMATED_DAYS,
    CASE
        WHEN O.ORDER_DELIVERED_CUSTOMER_DATE > O.ORDER_ESTIMATED_DELIVERY_DATE THEN 'Late'
        ELSE 'On Time'
    END AS DELIVERY_STATUS,
    GREATEST(DATEDIFF('day',O.ORDER_ESTIMATED_DELIVERY_DATE,O.ORDER_DELIVERED_CUSTOMER_DATE),0) AS DAYS_LATE
FROM ECOMMERCE_ANALYTICS.RAW.ORDERS O 
LEFT JOIN ECOMMERCE_ANALYTICS.RAW.CUSTOMERS C ON O.CUSTOMER_ID = C.CUSTOMER_ID
LEFT JOIN PAYMENT_AGG PA ON O.ORDER_ID = PA.ORDER_ID
LEFT JOIN REVIEW_CLEAN RC ON O.ORDER_ID = RC.ORDER_ID
LEFT JOIN ITEM_SUMMARY ITS ON O.ORDER_ID = ITS.ORDER_ID
LEFT JOIN CUSTOMER_HISTORY CH ON C.CUSTOMER_UNIQUE_ID = CH.CUSTOMER_UNIQUE_ID
WHERE O.ORDER_STATUS = 'delivered'
    AND O.ORDER_DELIVERED_CUSTOMER_DATE IS NOT NULL;

-- ═══════════════════════════════════════════════════════════════════
-- BASE VIEW 2: PRODUCT GRAIN (one row per item per order)
-- Used by: Dashboard 4
-- Grain: one item in one order = one row
-- ═══════════════════════════════════════════════════════════════════

CREATE OR REPLACE VIEW ECOMMERCE_ANALYTICS.ANALYTICS.V_PRODUCT_ANALYTICS AS
SELECT 
    O.ORDER_ID,
    O.ORDER_PURCHASE_TIMESTAMP,
    DATE_TRUNC('month',O.ORDER_PURCHASE_TIMESTAMP) AS ORDER_MONTH,
    QUARTER(O.ORDER_PURCHASE_TIMESTAMP) AS ORDER_QUARTER,
    YEAR(O.ORDER_PURCHASE_TIMESTAMP) AS ORDER_YEAR,
    C.CUSTOMER_STATE AS CUSTOMER_STATE,
    OI.ORDER_ITEM_ID AS ORDER_ITEM_ID,
    OI.PRODUCT_ID AS PRODUCT_ID,
    P.PRODUCT_CATEGORY_NAME,
    COALESCE(CT.PRODUCT_CATEGORY_NAME_ENGLISH,P.PRODUCT_CATEGORY_NAME) AS CATEGORY_ENGLISH,
    OI.PRICE AS ITEM_PRICE,
    OI.FREIGHT_VALUE AS FREIGHT_VALUE,
    OI.PRICE + OI.FREIGHT_VALUE AS ITEM_TOTAL,
    OI.SELLER_ID AS SELLER_ID,
    S.SELLER_CITY AS SELLER_CITY,
    S.SELLER_STATE AS SELLER_STATE,
    RC.REVIEW_SCORE,
    DATEDIFF('day',O.ORDER_PURCHASE_TIMESTAMP, O.ORDER_DELIVERED_CUSTOMER_DATE) AS DELIVERY_DAYS,
    CASE
        WHEN O.ORDER_DELIVERED_CUSTOMER_DATE > O.ORDER_ESTIMATED_DELIVERY_DATE THEN 'Late'
        ELSE 'On Time'
        END AS DELIVERY_STATUS

FROM ECOMMERCE_ANALYTICS.RAW.ORDERS O 
INNER JOIN ECOMMERCE_ANALYTICS.RAW.ORDER_ITEMS OI ON O.ORDER_ID = OI.ORDER_ID
INNER JOIN ECOMMERCE_ANALYTICS.RAW.CUSTOMERS C ON O.CUSTOMER_ID = C.CUSTOMER_ID
INNER JOIN ECOMMERCE_ANALYTICS.RAW.PRODUCTS P ON OI.PRODUCT_ID = P.PRODUCT_ID
LEFT JOIN ECOMMERCE_ANALYTICS.RAW.CATEGORY_TRANSLATION CT ON P.PRODUCT_CATEGORY_NAME = CT.PRODUCT_CATEGORY_NAME
LEFT JOIN ECOMMERCE_ANALYTICS.RAW.SELLERS S ON OI.SELLER_ID = S.SELLER_ID
LEFT JOIN (
    SELECT ORDER_ID, REVIEW_SCORE
    FROM ECOMMERCE_ANALYTICS.RAW.REVIEWS
    QUALIFY ROW_NUMBER() OVER (PARTITION BY ORDER_ID ORDER BY REVIEW_CREATION_DATE DESC) = 1
) RC ON O.ORDER_ID = RC.ORDER_ID
WHERE O.ORDER_STATUS = 'delivered'
    AND O.ORDER_DELIVERED_CUSTOMER_DATE IS NOT NULL;